### ISSUE TITLE
Haptic motor driver i2cwrite error after execution

### ISSUE THREAD

**Issue by HasiVS** [GeorgiaCharalampous/SpiceMate#3]
The driver throws "Could not write byte to 5a" after receiving a character to call the stopHaptic() function at the end of    [testmain.cpp.]

Could also be linked to stopHaptic() and stop() both being called after 1 character being received without waiting for second character?

**Comment by ViktoriyaKaleva** [comment]
The destructor is executed without being called.

**Comment by ViktoriyaKaleva** [comment]
The i2c bus tries to close two times in a row and results in a segmentation fault.

**Comment by ViktoriyaKaleva** [comment]
Segmentation fault resolved after added a check of if the motor is running.
