### ISSUE TITLE
Electromagnet actuation doesn't work even with logic-level shifter

### ISSUE THREAD

**Issue by HasiVS** [GeorgiaCharalampous/SpiceMate#4]
The magnet keeps drawing too much current from the sensor and the Pi can't handle it.

**Comment by HasiVS** [comment]
I think we should switch over to trying the servos to rotate the jars instead of using the electromagnet. @GeorgiaCharalampous how much would we need to rework the CAD model on Fusion to accommodate this?

**Comment by GeorgiaCharalampous** [comment]
Not too much I don't think. I can quickly work on it tomorrow and get some new parts printed

**Comment by HasiVS** [comment]
### Electromagnetic actuation abandoned
Servo motor will be used instead to rotate the jars for locking/unlocking mechanism instead of the electromagnetic gate idea.
