### ISSUE TITLE
VL6180X Driver: Continuous measurement is not working

### ISSUE THREAD

**Issue by HasiVS** [GeorgiaCharalampous/SpiceMate#5]
The initialization registers and I2C communication functions have all been checked, but the driver still only takes one measurement in continuous mode.

We need to check again if its a problem with the callback @ViktoriyaKaleva

**Comment by ViktoriyaKaleva** [comment]
The continuous mode needs to be triggered again after every interrupt. Writing in the registers at the end of the DataReady to stop and start the mode again fixes it.
