### ISSUE TITLE
Consider change the vibro motor from I2C to PWM.

### ISSUE THREAD

**Issue by ViktoriyaKaleva** [GeorgiaCharalampous/SpiceMate#7]
The I2C vibro motors are faulty (that's how they arrived). One is poorly soldered, the other starts only after nudging it.

**Comment by HasiVS** [comment]
Servo PWM driver using syfs is now fully functional at [SpiceMate/SYSF-PWM_Driver](https://github.com/GeorgiaCharalampous/SpiceMate/tree/SYSF-PWM_Driver).

Will attempt to run Vibro-4 class with ERM motor settings. If it doesn't work, syfs PWM driver can be used to run ERM motor too.

**Comment by HasiVS** [comment]
Converted Vibro4 class to run with ERM motor successfully. It is also produces much stronger vibrations than the LRA motor.

@ViktoriyaKaleva I think it's ready for merging into develop branch.

**Comment by HasiVS** [comment]
Changes merged without conflicts.
