### ISSUE TITLE
PCB issue

### ISSUE THREAD

**Issue by ViktoriyaKaleva** [GeorgiaCharalampous/SpiceMate#9]
Need to redo the PCB because the pi pinout is mirrored and the servo footprint is not routed properly.

**Comment by HasiVS** [comment]
I will fix this on Altium Designer and try to get a new one fabricated on Monday.

**Comment by HasiVS** [comment]
New PCB has been fabricated with corrected Raspberry Pi pinout, routing for all final product hardware and a centralised power source via USB-B.
